# -*- coding: utf-8 -*-
"""ыыы.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1soJGd6nM0Cd1G6QnU92awN-WDzbL55Q-
"""

import time

# Функция для вычисления выражения
def calculate_expression(x):
    return (x * x) - (x * x) + (x * 4) - (x * 5) + x + x

def main():
    while True:
        try:
            # Получаем количество итераций от пользователя
            n = int(input("Введите пажалуста количество итераций (n): "))

            if n < 0:
                print("Не балуйся!")
                continue

            # Засекаем время начала выполнения
            start_time = time.time()

            result = 0.0

            # Выполняем вычисление n раз
            for i in range(n):
                result = calculate_expression(i)

            # Засекаем время окончания
            end_time = time.time()
            elapsed_time = (end_time - start_time) * 1_000_000  # в микросекундах

            print(f"Последний результат вычислений: {result}")
            print(f"Время выполнения: {elapsed_time:.2f} мкс")

        except ValueError:
            print("Это не число!. Пока")
            break

        # Спрашиваем, нужно ли повторить расчет
        choice = input("Хочешь повторить?) (y/n): ")
        if choice.lower() != 'y':
            break

if __name__ == "__main__":
    main()